/**
 * WAhubX .env Generator (installer post-install step · Day 3-4)
 *
 * 从 Inno Setup 向导端口配置生成 backend .env · 自动生成强密码
 *
 * Usage: node generate-env.js --mode local --app-port 3000
 *        --pg-port 5433 --redis-port 6380 --install-dir <path>
 *
 * M10 note: APP_ENCRYPTION_KEY 会在首次启动后被 MasterKeyMigrationService 自动迁移到
 *           MachineBoundMasterKey · env key 仅作 bootstrap · 迁移完成后可从 .env 移除.
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

function parseArgs() {
  const args = process.argv.slice(2);
  const params = {};
  for (let i = 0; i < args.length; i += 2) {
    const key = args[i].replace(/^--/, '');
    params[key] = args[i + 1];
  }
  return params;
}

function generateHex(length) {
  return crypto.randomBytes(length).toString('hex');
}

function generatePassword(length = 24) {
  // 去掉易混淆字符 (Il1O0) · DB 密码不含 shell 特殊字符
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789';
  const bytes = crypto.randomBytes(length);
  let result = '';
  for (let i = 0; i < length; i++) {
    result += chars[bytes[i] % chars.length];
  }
  return result;
}

function main() {
  const params = parseArgs();

  // WAhubX V1 只 local 模式 (Inno .iss 已砍 Cloud 选项)
  const appPort = params['app-port'] || '3000';
  const pgPort = params['pg-port'] || '5433';
  const redisPort = params['redis-port'] || '6380';
  const installDir = params['install-dir'] || process.cwd();

  // .env 在 app/backend/.env (升级时 app/ 替换但 .env 该保留 · 单独 install-dir 根)
  // 决策: 放 installDir/.env · 不嵌 app/backend/ · 升级不丢配置
  const envPath = path.join(installDir, '.env');

  // 已存在 .env · 保留已有密钥避免密钥轮换破坏加密数据
  const existing = {};
  if (fs.existsSync(envPath)) {
    const content = fs.readFileSync(envPath, 'utf-8');
    for (const line of content.split(/\r?\n/)) {
      const m = line.match(/^([A-Z_]+)=(.*)$/);
      if (m) existing[m[1]] = m[2];
    }
    console.log('[INFO] 检测到已有 .env · 保留原有密钥 (APP_ENCRYPTION_KEY / JWT_* / DB_PASSWORD)');
  }

  const jwtAccessSecret = existing.JWT_ACCESS_SECRET || generateHex(32); // 64 hex
  const jwtRefreshSecret = existing.JWT_REFRESH_SECRET || generateHex(32);
  const appEncryptionKey = existing.APP_ENCRYPTION_KEY || generateHex(32); // 64 hex · M10 过渡用
  const dbPassword = existing.DB_PASSWORD || generatePassword(20);

  const envContent = `# ============================================================
# WAhubX Configuration · Auto-generated by installer
# Generated: ${new Date().toISOString()}
# Install dir: ${installDir}
# ============================================================

# ──── Server ────
NODE_ENV=production
PORT=${appPort}
LOG_LEVEL=info

# ──── Database (PostgreSQL portable · installer/deps/pgsql-portable) ────
DB_HOST=127.0.0.1
DB_PORT=${pgPort}
DB_USERNAME=wahubx
DB_PASSWORD=${dbPassword}
DB_DATABASE=wahubx

# ──── JWT ────
JWT_ACCESS_SECRET=${jwtAccessSecret}
JWT_REFRESH_SECRET=${jwtRefreshSecret}
JWT_ACCESS_TTL=15m
JWT_REFRESH_TTL=7d

# ──── Auth lockout ────
LOGIN_MAX_ATTEMPTS=5
LOGIN_LOCKOUT_SECONDS=900
BCRYPT_ROUNDS=12

# ──── Redis / BullMQ ────
REDIS_HOST=127.0.0.1
REDIS_PORT=${redisPort}
REDIS_PASSWORD=
REDIS_DB=0

# ──── Scheduler (M3) ────
SCHEDULER_MAX_CONCURRENCY=6
SCHEDULER_POLL_INTERVAL_MS=3000
SCHEDULER_NIGHT_WINDOW_START=02:00
SCHEDULER_NIGHT_WINDOW_END=06:00

# ──── AI (M6) · Master key · M10 自动迁移到 MachineBound 后可删此行 ────
APP_ENCRYPTION_KEY=${appEncryptionKey}

# ──── Warmup (M5) · Health (M8) 定时 ────
# 无需改, 用默认. 调试用可缩短
# WARMUP_CALENDAR_INTERVAL_MS=3600000
# HEALTH_RESCORE_INTERVAL_MS=300000

# ──── M10 Backup ────
BACKUP_DAILY_CRON_HOUR=3
BACKUP_RETENTION_DAYS=7
# BACKUP_INCLUDE_MEDIA=false  (默认 false · 入站媒体不进每日 zip)

# ──── M11 Update ────
# WAHUBX_PG_CONTAINER / WAHUBX_PG_USER / WAHUBX_PG_DB · 覆盖 docker exec pg_dump/psql 默认
# 本地 portable pg 场景用 pg_ctl 不用 docker · V1.1 评估
`;

  fs.mkdirSync(path.dirname(envPath), { recursive: true });
  fs.writeFileSync(envPath, envContent, 'utf-8');

  console.log(`[OK] .env generated: ${envPath}`);
  console.log(`  Port: ${appPort} (backend)`);
  console.log(`  PG Port: ${pgPort}`);
  console.log(`  Redis Port: ${redisPort}`);
  console.log(`  DB User: wahubx · Password: ${'*'.repeat(dbPassword.length)}`);
  console.log(`  APP_ENCRYPTION_KEY: ${'*'.repeat(16)}... (M10 迁移后可删)`);
}

main();
